<a href="https://colab.research.google.com/github/CesarMauriciof/Electiva-Profesional-I/blob/main/Importaci%C3%B3n_y_manejo_de_datos_Electiva_pro_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ELECTIVA PROFESIONAL II

En este notebook revisaremos los principales métodos de la libreria `pandas` de python que nos permite leer y manipular datos distintos formatos. En particular trabajaremos los siguientes temas:

- Importación e inspección de datos estructurados en formatos `.csv` y `.xlss`
- Importación y manipulación de datos semiestructurados en formatos `.json`

La documentación de pandas asociada a métodos de lectura y escritura de datos, la podemos consular en el siguiente enlace:

https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

In [ ]:
# En primer lugar importamos la librerias a utilizar
import pandas as pd

# 1. Importación e inspección de datos estructurados

Para realizar la lectura e inspección de datos estructurados, consideramos como ejemplo el siguiente dataset:

https://raw.githubusercontent.com/carloseruiz/ElectivaII_Introduccion_Ciencia_Datos/refs/heads/main/productos.csv

- Listado de productos de un negocio de artículos de libreria, cada uno con un nombre, código, marca, costo, precio de venta y número de venta y número de unidades disponibles

Este conjunto de datos estar disponible en distintos formatos estructurados como `.csv` o `xlsx` propio de hojas de cálculo como Excel, Google Sheets, entre otras.

## 1.1 Lectura de datos en formato de texto plano (csv)

https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [ ]:
data = "https://raw.githubusercontent.com/carloseruiz/ElectivaII_Introduccion_Ciencia_Datos/refs/heads/main/productos.csv"

In [ ]:
df = pd.read_csv(data, sep=";")

In [ ]:
df

,Producto,Marca,CodigoSKU,Costo,PrecioVenta,Unidades
0,Cuaderno lineas,SVLUS,1003789,1210,1452.0,116
1,Cuaderno cuadros,SVLUS,1929835,1210,1452.0,165
2,Lapiz grafito,Lappau,1366925,470,564.0,194
3,Goma de borrar,Lappau,1461758,285,342.0,131
4,Corchetera,Officia,1835948,3250,3900.0,190
5,Pincel fino,ArtM,1992659,990,1188.0,139
6,Pincel grueso,ArtM,1959137,1100,1320.0,198
7,Acrilico 6 colores,ArtM,1124149,7320,8784.0,45
8,Mezclador 6,ArtM,1954385,890,1068.0,138
9,Toner,TechOf,1301317,15230,18276.0,145
10,Resma carta,MultiOffice,1987180,4580,5496.0,7
11,Corrector blanco,MultiOffice,1062342,2565,3078.0,80
12,Tijera escolar,Lappau,1939778,2200,2640.0,75
13,Destacador amarillo,Lappau,1918078,1320,1584.0,124
14,Destacador verde,Lappau,1028765,1320,1584.0,21
15,Block notas,MultiPaper,1375330,3128,3753.6,42
16,Marcador pizarra azul,Officia,1045223,1530,1836.0,131
17,Marcador pizarra negro,Officia,1818443,1530,1836.0,154
18,Perforadora,Officia,1302786,6430,7716.0,29
19,Clips 100U,MultiOffice,1967352,650,780.0,128
20,Clips 1000U,MultiOffice,1912077,5235,6282.0,19
21,Borrador,Officia,1875869,6780,8136.0,25
22,Barra pegamento,ArtM,1898500,765,918.0,52
23,Bolígrafo azul,Lappau,1039715,525,630.0,168
24,Bolígrafo negro,Lappau,1590428,530,636.0,142
25,Bolígrafo rojo,Lappau,1760135,530,636.0,73

## 1.2 Lectura de datos en formatos Excel (.xlsx)

In [ ]:
df = pd.read_excel("/content/productos.xlsx", sheet_name="productos", skiprows=2)

In [ ]:
df

,Producto,Marca,CodigoSKU,Costo,PrecioVenta,Unidades
0,Cuaderno lineas,SVLUS,1003789,1210,1452.0,116
1,Cuaderno cuadros,SVLUS,1929835,1210,1452.0,165
2,Lapiz grafito,Lappau,1366925,470,564.0,194
3,Goma de borrar,Lappau,1461758,285,342.0,131
4,Corchetera,Officia,1835948,3250,3900.0,190
5,Pincel fino,ArtM,1992659,990,1188.0,139
6,Pincel grueso,ArtM,1959137,1100,1320.0,198
7,Acrilico 6 colores,ArtM,1124149,7320,8784.0,45
8,Mezclador 6,ArtM,1954385,890,1068.0,138
9,Toner,TechOf,1301317,15230,18276.0,145
10,Resma carta,MultiOffice,1987180,4580,5496.0,7
11,Corrector blanco,MultiOffice,1062342,2565,3078.0,80
12,Tijera escolar,Lappau,1939778,2200,2640.0,75
13,Destacador amarillo,Lappau,1918078,1320,1584.0,124
14,Destacador verde,Lappau,1028765,1320,1584.0,21
15,Block notas,MultiPaper,1375330,3128,3753.6,42
16,Marcador pizarra azul,Officia,1045223,1530,1836.0,131
17,Marcador pizarra negro,Officia,1818443,1530,1836.0,154
18,Perforadora,Officia,1302786,6430,7716.0,29
19,Clips 100U,MultiOffice,1967352,650,780.0,128
20,Clips 1000U,MultiOffice,1912077,5235,6282.0,19
21,Borrador,Officia,1875869,6780,8136.0,25
22,Barra pegamento,ArtM,1898500,765,918.0,52
23,Bol√≠grafo azul,Lappau,1039715,525,630.0,168
24,Bol√≠grafo negro,Lappau,1590428,530,636.0,142
25,Bol√≠grafo rojo,Lappau,1760135,530,636.0,73

## 1.2 Revisión e inspección de los datos importados (DataFrame)

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html



- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html



- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html



- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html



- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html



- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html

La función `.info()` del objeto DatraFrame de pandas, me entraga información general del set de datos como: cantidad de filas, cantidad de datos nulos por cada fila, nombres de columnas y tipos de datos almacenados en cada columna

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Producto     26 non-null     object
 1   Marca        26 non-null     object
 2   CodigoSKU    26 non-null     int64
 3   Costo        26 non-null     int64
 4   PrecioVenta  26 non-null     float64
 5   Unidades     26 non-null     int64
dtypes: float64(1), int64(3), object(2)
memory usage: 1.3+ KB

La función `.columns` me entrega un listado de los envabezados de las columnas de DataFrame

In [ ]:
df.columns

Index(['Producto', 'Marca', 'CodigoSKU', 'Costo', 'PrecioVenta', 'Unidades'], dtype='object')

La función `.head()` me permite visulizar por defecto las 5 primeras filas de mi dataset. Sin embargo, la cantidad de datos a visualizar se puede configurar

In [ ]:
df.head()

           Producto    Marca  CodigoSKU  Costo  PrecioVenta  Unidades
0   Cuaderno lineas    SVLUS    1003789   1210       1452.0       116
1  Cuaderno cuadros    SVLUS    1929835   1210       1452.0       165
2     Lapiz grafito   Lappau    1366925    470        564.0       194
3    Goma de borrar   Lappau    1461758    285        342.0       131
4        Corchetera  Officia    1835948   3250       3900.0       190

La función `.tail()` me permite visulizar por defecto las 5 últimas filas de mi dataset. Sin embargo, la cantidad de datos a visualizar se puede configurar

In [ ]:
df.tail()

            Producto    Marca  CodigoSKU  Costo  PrecioVenta  Unidades
21          Borrador  Officia    1875869   6780       8136.0        25
22   Barra pegamento     ArtM    1898500    765        918.0        52
23   Bol√≠grafo azul   Lappau    1039715    525        630.0       168
24  Bol√≠grafo negro   Lappau    1590428    530        636.0       142
25   Bol√≠grafo rojo   Lappau    1760135    530        636.0        73

La función `.sample()` me permite traer un conjunto de registros al azar

In [ ]:
df.sample(5)

,Producto,Marca,CodigoSKU,Costo,PrecioVenta,Unidades
16,Marcador pizarra azul,Officia,1045223,1530,1836.0,131
11,Corrector blanco,MultiOffice,1062342,2565,3078.0,80
18,Perforadora,Officia,1302786,6430,7716.0,29
7,Acrilico 6 colores,ArtM,1124149,7320,8784.0,45
5,Pincel fino,ArtM,1992659,990,1188.0,139

In [ ]:
df.describe()

          CodigoSKU         Costo   PrecioVenta    Unidades
count  2.600000e+01     26.000000     26.000000   26.000000
mean   1.594304e+06   2752.807692   3303.369231  105.038462
std    3.757840e+05   3299.660007   3959.592008   60.166755
min    1.003789e+06    285.000000    342.000000    7.000000
25%    1.301684e+06    796.250000    955.500000   46.750000
50%    1.789289e+06   1320.000000   1584.000000  126.000000
75%    1.926896e+06   3219.500000   3863.400000  144.250000
max    1.992659e+06  15230.000000  18276.000000  198.000000

La función `.describe()` permite generar un reporte estadístico:

# 2. Importación, revisión e inspección de datos semiestructurados

## 2.1 Importación de datos en formato JSON

Revisaremos unos ejemplos generales de lectura y manipulación de datos de tipo JSON

In [ ]:
#Esta libreria nos permite abrir y visualizar un archivo en formato JSON
import json

## Ejemplo 1: Dataset de Productos

In [ ]:
json_productos = json.load(open('/content/productos.json', 'r'))

In [ ]:
json_productos

[{'Producto': 'Cuaderno lineas',
  'Marca': 'SVLUS',
  'CodigoSKU': 1003789,
  'Costo': 1210,
  'PrecioVenta': 1452,
  'Unidades': 116},
 {'Producto': 'Cuaderno cuadros',
  'Marca': 'SVLUS',
  'CodigoSKU': 1929835,
  'Costo': 1210,
  'PrecioVenta': 1452,
  'Unidades': 165},
 {'Producto': 'Lapiz grafito',
  'Marca': 'Lappau',
  'CodigoSKU': 1366925,
  'Costo': 470,
  'PrecioVenta': 564,
  'Unidades': 194},
 {'Producto': 'Goma de borrar',
  'Marca': 'Lappau',
  'CodigoSKU': 1461758,
  'Costo': 285,
  'PrecioVenta': 342,
  'Unidades': 131},
 {'Producto': 'Corchetera',
  'Marca': 'Officia',
  'CodigoSKU': 1835948,
  'Costo': 3250,
  'PrecioVenta': 3900,
  'Unidades': 190},
 {'Producto': 'Pincel fino',
  'Marca': 'ArtM',
  'CodigoSKU': 1992659,
  'Costo': 990,
  'PrecioVenta': 1188,
  'Unidades': 139},
 {'Producto': 'Pincel grueso',
  'Marca': 'ArtM',
  'CodigoSKU': 1959137,
  'Costo': 1100,
  'PrecioVenta': 1320,
  'Unidades': 198},
 {'Producto': 'Acrilico 6 colores',
  'Marca': 'ArtM',
  'CodigoSKU': 1124149,
  'Costo': 7320,
  'PrecioVenta': 8784,
  'Unidades': 45},
 {'Producto': 'Mezclador 6',
  'Marca': 'ArtM',
  'CodigoSKU': 1954385,
  'Costo': 890,
  'PrecioVenta': 1068,
  'Unidades': 138},
 {'Producto': 'Toner',
  'Marca': 'TechOf',
  'CodigoSKU': 1301317,
  'Costo': 15230,
  'PrecioVenta': 18276,
  'Unidades': 145},
 {'Producto': 'Resma carta',
  'Marca': 'MultiOffice',
  'CodigoSKU': 1987180,
  'Costo': 4580,
  'PrecioVenta': 5496,
  'Unidades': 7},
 {'Producto': 'Corrector blanco',
  'Marca': 'MultiOffice',
  'CodigoSKU': 1062342,
  'Costo': 2565,
  'PrecioVenta': 3078,
  'Unidades': 80},
 {'Producto': 'Tijera escolar',
  'Marca': 'Lappau',
  'CodigoSKU': 1939778,
  'Costo': 2200,
  'PrecioVenta': 2640,
  'Unidades': 75},
 {'Producto': 'Destacador amarillo',
  'Marca': 'Lappau',
  'CodigoSKU': 1918078,
  'Costo': 1320,
  'PrecioVenta': 1584,
  'Unidades': 124},
 {'Producto': 'Destacador verde',
  'Marca': 'Lappau',
  'CodigoSKU': 1028765,
  'Costo': 1320,
  'PrecioVenta': 1584,
  'Unidades': 21},
 {'Producto': 'Block notas',
  'Marca': 'MultiPaper',
  'CodigoSKU': 1375330,
  'Costo': 3128,
  'PrecioVenta': 3753.6,
  'Unidades': 42},
 {'Producto': 'Marcador pizarra azul',
  'Marca': 'Officia',
  'CodigoSKU': 1045223,
  'Costo': 1530,
  'PrecioVenta': 1836,
  'Unidades': 131},
 {'Producto': 'Marcador pizarra negro',
  'Marca': 'Officia',
  'CodigoSKU': 1818443,
  'Costo': 1530,
  'PrecioVenta': 1836,
  'Unidades': 154},
 {'Producto': 'Perforadora',
  'Marca': 'Officia',
  'CodigoSKU': 1302786,
  'Costo': 6430,
  'PrecioVenta': 7716,
  'Unidades': 29},
 {'Producto': 'Clips 100U',
  'Marca': 'MultiOffice',
  'CodigoSKU': 1967352,
  'Costo': 650,
  'PrecioVenta': 780,
  'Unidades': 128},
 {'Producto': 'Clips 1000U',
  'Marca': 'MultiOffice',
  'CodigoSKU': 1912077,
  'Costo': 5235,
  'PrecioVenta': 6282,
  'Unidades': 19},
 {'Producto': 'Borrador',
  'Marca': 'Officia',
  'CodigoSKU': 1875869,
  'Costo': 6780,
  'PrecioVenta': 8136,
  'Unidades': 25},
 {'Producto': 'Barra pegamento',
  'Marca': 'ArtM',
  'CodigoSKU': 1898500,
  'Costo': 765,
  'PrecioVenta': 918,
  'Unidades': 52},
 {'Producto': 'Bolígrafo azul',
  'Marca': 'Lappau',
  'CodigoSKU': 1039715,
  'Costo': 525,
  'PrecioVenta': 630,
  'Unidades': 168},
 {'Producto': 'Bolígrafo negro',
  'Marca': 'Lappau',
  'CodigoSKU': 1590428,
  'Costo': 530,
  'PrecioVenta': 636,
  'Unidades': 142},
 {'Producto': 'Bolígrafo rojo',
  'Marca': 'Lappau',
  'CodigoSKU': 1760135,
  'Costo': 530,
  'PrecioVenta': 636,
  'Unidades': 73}]

En pandas, podemso crear un DataFrame a partir de un objeto  de tipo JSON.
`Nota: Un objeto JSON es el equivalente a un diccionario en python`

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(json_productos)

In [ ]:
df

,Producto,Marca,CodigoSKU,Costo,PrecioVenta,Unidades
0,Cuaderno lineas,SVLUS,1003789,1210,1452.0,116
1,Cuaderno cuadros,SVLUS,1929835,1210,1452.0,165
2,Lapiz grafito,Lappau,1366925,470,564.0,194
3,Goma de borrar,Lappau,1461758,285,342.0,131
4,Corchetera,Officia,1835948,3250,3900.0,190
5,Pincel fino,ArtM,1992659,990,1188.0,139
6,Pincel grueso,ArtM,1959137,1100,1320.0,198
7,Acrilico 6 colores,ArtM,1124149,7320,8784.0,45
8,Mezclador 6,ArtM,1954385,890,1068.0,138
9,Toner,TechOf,1301317,15230,18276.0,145
10,Resma carta,MultiOffice,1987180,4580,5496.0,7
11,Corrector blanco,MultiOffice,1062342,2565,3078.0,80
12,Tijera escolar,Lappau,1939778,2200,2640.0,75
13,Destacador amarillo,Lappau,1918078,1320,1584.0,124
14,Destacador verde,Lappau,1028765,1320,1584.0,21
15,Block notas,MultiPaper,1375330,3128,3753.6,42
16,Marcador pizarra azul,Officia,1045223,1530,1836.0,131
17,Marcador pizarra negro,Officia,1818443,1530,1836.0,154
18,Perforadora,Officia,1302786,6430,7716.0,29
19,Clips 100U,MultiOffice,1967352,650,780.0,128
20,Clips 1000U,MultiOffice,1912077,5235,6282.0,19
21,Borrador,Officia,1875869,6780,8136.0,25
22,Barra pegamento,ArtM,1898500,765,918.0,52
23,Bolígrafo azul,Lappau,1039715,525,630.0,168
24,Bolígrafo negro,Lappau,1590428,530,636.0,142
25,Bolígrafo rojo,Lappau,1760135,530,636.0,73

## Ejemplo 2: Dataset de locales comerciales

In [ ]:
json_locales = json.load(open('/content/locales_comerciales.json', 'r'))

In [ ]:
df = pd.DataFrame(json_electronica)

Una característica de los archivos en formato JSON, es precisamente que traen información anidada, es decir que dentro de un atributo podemos tener uno o más objeto de tipo JSON.

Para poder visualizar este tipo de datos, es conveniente `aplanar ` (`flattened`) o normalizar la información, de manera que se pueda visulizar y almacenar correctamente en un DataFrame

Para realizar este proceso utilizamos la función `json_normalize()` de la librería pandas.

https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html

In [ ]:
df

,local,vendedores,info_local,clientes,encargados
0,Colina,20,"{'direccion': 'Las Condes 435', 'telefono': '5...","[{'nombre': 'Luis', 'apellido': 'Perez', 'mail...","{'gerente': 'Luis Perez', 'ventas': 'Mario Gon..."
1,Cisterna,10,"{'direccion': 'Las Gaviotas 872', 'telefono': ...","[{'nombre': 'Pedro', 'apellido': 'Sanchez', 'm...","{'gerente': 'Marta Vasquez', 'ventas': 'Sandra..."

In [ ]:
pd.json_normalize(json_locales)

,local,vendedores,clientes,info_local.direccion,info_local.telefono,encargados.gerente,encargados.ventas,encargados.operaciones
0,Colina,20,"[{'nombre': 'Luis', 'apellido': 'Perez', 'mail...",Las Condes 435,5698727564,Luis Perez,Mario Gonzalez,Paz Blanco
1,Cisterna,10,"[{'nombre': 'Pedro', 'apellido': 'Sanchez', 'm...",Las Gaviotas 872,5698727564,Marta Vasquez,Sandra Carrasco,Marcial Santos

In [ ]:
pd.json_normalize(json_locales, record_path=['clientes'])

,nombre,apellido,mail,comprasMes,productos.Cuaderno cuadros,telefono,productos.Lapiz grafito,productos.Goma de borrar,productos.Impresora
0,Luis,Perez,luisperez@mail.com,178540.0,18.0,NaN,NaN,NaN,NaN
1,Victoria,Solar,vsolar@mail.com,237549.0,5.0,56962899045,10.0,8.0,NaN
2,Pedro,Sanchez,psanchez@mail.com,654.0,NaN,NaN,25.0,NaN,2.0
3,Luciana,Ramirez,luciram@mail.com,NaN,32.0,5687763925,NaN,9.0,NaN

In [ ]:
df_clientes = pd.json_normalize(json_locales, record_path=['clientes'], meta=['local'])

In [ ]:
df_clientes

,nombre,apellido,mail,comprasMes,productos.Cuaderno cuadros,telefono,productos.Lapiz grafito,productos.Goma de borrar,productos.Impresora,local
0,Luis,Perez,luisperez@mail.com,178540.0,18.0,NaN,NaN,NaN,NaN,Colina
1,Victoria,Solar,vsolar@mail.com,237549.0,5.0,56962899045,10.0,8.0,NaN,Colina
2,Pedro,Sanchez,psanchez@mail.com,654.0,NaN,NaN,25.0,NaN,2.0,Cisterna
3,Luciana,Ramirez,luciram@mail.com,NaN,32.0,5687763925,NaN,9.0,NaN,Cisterna

In [ ]:
df_clientes.to_json('lista_clientes-v2.json')